version: "3"
services:
  python:
    image: python:3.6.3-onbuild
    command: bash
    volumes:
      - .:/usr/src/app

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --requirepass longitude
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru
    restart: unless-stopped

  postgres:
    image: kartoza/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: longitude
      POSTGRES_PASS: longitude
    volumes:
      - ./data/:/var/lib/postgresql/data/pgdata
