version: '3.7'

services:
  postgis:
    image: geographica/postgis:tasty_termite
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgis-data:/data
      - ./:/usr/src/app
    restart: unless-stopped

  redis:
    image: redis:5-alpine
    env_file:
      - .env
    ports:
      - '6379:6379'
    restart: unless-stopped
    command:
      - redis-server
      - --maxmemory 256mb
      - --maxmemory-policy allkeys-lru

  bash:
    build:
      context: .
      args:
        ENVIRONMENT: local
    image: longitude:latest
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    command: bash

  jupyter:
    build:
      context: .
      args:
        ENVIRONMENT: local
    image: longitude:latest
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
        - '8888:8888'
    restart: unless-stopped
    command: jupyter

  lint:
    build:
      context: .
      args:
        ENVIRONMENT: local
    image: longitude:latest
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    command: lint

  test:
    build:
      context: .
      args:
        ENVIRONMENT: local
    image: longitude:latest
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    command: test

volumes:
  postgis-data:
